{
 "title": "Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(target_info,k8s_cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(target_info{k8s_cluster_name=\"$cluster\"},k8s_namespace_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (k8s_cluster_name) (\n    k8s_container_cpu_request{k8s_cluster_name=~\"${cluster}\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (k8s_cluster_name, instance) (\n    k8s_node_cpu_usage{k8s_cluster_name=~\"${cluster}\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "group by (k8s_cluster_name, k8s_namespace_name) (\n    target_info{\n        k8s_cluster_name=~\"${cluster}\",\n        k8s_namespace_name=~\"${namespace}\"\n    }\n)",
     "legendFormat": "{{k8s_cluster_name}} - {{k8s_namespace_name}}"
    }
   ]
  }
 ]
}